SELECT PESS.PESS_NM_PESSOA AS MEDICO, COUNT(AGEN.AGEN_ID_AGENDAMENTO) AS QUANTIDADE_AGENDAMENTOS
FROM PESSOA AS PESS
LEFT JOIN MEDICO AS MEDI
ON PESS.PESS_ID_PESSOA = MEDI.PESS_ID_PESSOA
LEFT JOIN ESPECIALIDADE_MEDICO AS ESME
ON MEDI.PESS_ID_PESSOA = ESME.PESS_ID_PESSOA
RIGHT JOIN ESPECIALIDADE AS ESPE
ON ESPE.ESPE_NM_ESPECIALIDADE = 'Cardiologia'
LEFT JOIN ESPECIALIDADE_MEDICO
ON ESPE.ESPE_ID_ESPECIALIDADE = ESME.ESPE_ID_ESPECIALIDADE
LEFT JOIN CONSULTA AS CONS
ON ESME.PESS_ID_PESSOA = CONS.PESS_ID_PESSOA_MEDICO
LEFT JOIN AGENDAMENTO AS AGEN
ON CONS.CONS_ID_CONSULTA = AGEN.CONS_ID_CONSULTA
AND AGEN.AGEN_DT_AGENDAMENTO >= '2018-04-01'
AND AGEN.AGEN_DT_AGENDAMENTO <= '2019-03-31'
GROUP BY AGEN.AGEN_ID_AGENDAMENTO
HAVING QUANTIDADE_AGENDAMENTOS > 5;



-- SELECT PESS.PESS_NM_PESSOA AS MEDICO, CONS.PESS_ID_PESSOA_MEDICO AS MEDICO_ID, AGEN.AGEN_ID_AGENDAMENTO AS AGENDAMENTO
-- FROM PESSOA AS PESS
-- LEFT JOIN MEDICO AS MEDI
-- ON PESS.PESS_ID_PESSOA = MEDI.PESS_ID_PESSOA
-- LEFT JOIN ESPECIALIDADE_MEDICO AS ESME
-- ON MEDI.PESS_ID_PESSOA = ESME.PESS_ID_PESSOA
-- RIGHT JOIN ESPECIALIDADE AS ESPE
-- ON ESPE.ESPE_NM_ESPECIALIDADE = 'Cardiologia'
-- LEFT JOIN ESPECIALIDADE_MEDICO
-- ON ESPE.ESPE_ID_ESPECIALIDADE = ESME.ESPE_ID_ESPECIALIDADE
-- LEFT JOIN CONSULTA AS CONS
-- ON ESME.PESS_ID_PESSOA = CONS.PESS_ID_PESSOA_MEDICO
-- LEFT JOIN AGENDAMENTO AS AGEN
-- ON CONS.CONS_ID_CONSULTA = AGEN.CONS_ID_CONSULTA
-- AND AGEN.AGEN_DT_AGENDAMENTO >= '2018-04-01'
-- AND AGEN.AGEN_DT_AGENDAMENTO <= '2019-03-31';

-- IMPLEMENTE UM RELATÃ“RIO QUE INFORME QUAIS FORAM OS MÃ‰DICOS, 
-- CUJA SUA ESPECIALIDADE SEJA CARDIOLOGIA, 
-- QUE REALIZARAM MAIS DE 5 ATENDIMENTOS 
-- ENTRE PERIODO DE 01/04/2018 E 31/03/2019.